services:
  email-forwarder:
    build: .
    container_name: email-forwarder-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./.env
  